#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '/home/roboy/workspace/roboy_fpga_interrupt/roboy_de10_nano_soc/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'user_input_device_0', class 'user_input_device'
 * The macros are prefixed with 'USER_INPUT_DEVICE_0_'.
 * The prefix is the slave descriptor.
 */
#define USER_INPUT_DEVICE_0_COMPONENT_TYPE user_input_device
#define USER_INPUT_DEVICE_0_COMPONENT_NAME user_input_device_0
#define USER_INPUT_DEVICE_0_BASE 0x0
#define USER_INPUT_DEVICE_0_SPAN 1
#define USER_INPUT_DEVICE_0_END 0x0
#define USER_INPUT_DEVICE_0_IRQ 31

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x1000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x1007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1510529191


#endif /* _ALTERA_HPS_0_H_ */
