# TCL File Generated by Component Editor 18.1
# Fri Jan 10 17:07:53 CET 2020
# DO NOT MODIFY


# 
# MYOQuad "MYOQuad" v1.0
# Simon Trendel 2020.01.10.17:07:53
# myobrick winch displacement using two differential position encoders
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module MYOQuad
# 
set_module_property DESCRIPTION "myobrick winch displacement using two differential position encoders"
set_module_property NAME MYOQuad
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Simon Trendel"
set_module_property DISPLAY_NAME MYOQuad
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MyoQuad
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file myoQuad.v VERILOG PATH ip/roboy_fpga_code/quadrature/myoQuad.v TOP_LEVEL_FILE
add_fileset_file quad.v VERILOG PATH ip/roboy_fpga_code/quadrature/quad.v
add_fileset_file grp_debouncer.vhd VHDL PATH ip/roboy_fpga_code/myo_control/spi_master_slave/trunk/rtl/spi_master_slave/grp_debouncer.vhd


# 
# parameters
# 
add_parameter CLOCK_FREQ_HZ INTEGER 50000000
set_parameter_property CLOCK_FREQ_HZ DEFAULT_VALUE 50000000
set_parameter_property CLOCK_FREQ_HZ DISPLAY_NAME CLOCK_FREQ_HZ
set_parameter_property CLOCK_FREQ_HZ TYPE INTEGER
set_parameter_property CLOCK_FREQ_HZ UNITS None
set_parameter_property CLOCK_FREQ_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLOCK_FREQ_HZ HDL_PARAMETER true
add_parameter DEBOUNCE_TICKS INTEGER 5
set_parameter_property DEBOUNCE_TICKS DEFAULT_VALUE 5
set_parameter_property DEBOUNCE_TICKS DISPLAY_NAME DEBOUNCE_TICKS
set_parameter_property DEBOUNCE_TICKS TYPE INTEGER
set_parameter_property DEBOUNCE_TICKS UNITS None
set_parameter_property DEBOUNCE_TICKS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 4
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end quad0_Aneg quad0_aneg Input 1
add_interface_port conduit_end quad0_Apos quad0_apos Input 1
add_interface_port conduit_end quad0_Bneg quad0_bneg Input 1
add_interface_port conduit_end quad0_Bpos quad0_bpos Input 1
add_interface_port conduit_end quad1_Aneg quad1_aneg Input 1
add_interface_port conduit_end quad1_Apos quad1_apos Input 1
add_interface_port conduit_end quad1_Bneg quad1_bneg Input 1
add_interface_port conduit_end quad1_Bpos quad1_bpos Input 1

