	soc_system u0 (
		.auxilliary_i2c_0_conduit_end_scl            (<connected-to-auxilliary_i2c_0_conduit_end_scl>),            //        auxilliary_i2c_0_conduit_end.scl
		.auxilliary_i2c_0_conduit_end_sda            (<connected-to-auxilliary_i2c_0_conduit_end_sda>),            //                                    .sda
		.auxilliary_i2c_1_conduit_end_scl            (<connected-to-auxilliary_i2c_1_conduit_end_scl>),            //        auxilliary_i2c_1_conduit_end.scl
		.auxilliary_i2c_1_conduit_end_sda            (<connected-to-auxilliary_i2c_1_conduit_end_sda>),            //                                    .sda
		.auxilliary_i2c_2_conduit_end_scl            (<connected-to-auxilliary_i2c_2_conduit_end_scl>),            //        auxilliary_i2c_2_conduit_end.scl
		.auxilliary_i2c_2_conduit_end_sda            (<connected-to-auxilliary_i2c_2_conduit_end_sda>),            //                                    .sda
		.auxilliary_i2c_3_conduit_end_scl            (<connected-to-auxilliary_i2c_3_conduit_end_scl>),            //        auxilliary_i2c_3_conduit_end.scl
		.auxilliary_i2c_3_conduit_end_sda            (<connected-to-auxilliary_i2c_3_conduit_end_sda>),            //                                    .sda
		.balljoint_0_conduit_end_scl                 (<connected-to-balljoint_0_conduit_end_scl>),                 //             balljoint_0_conduit_end.scl
		.balljoint_0_conduit_end_sda                 (<connected-to-balljoint_0_conduit_end_sda>),                 //                                    .sda
		.balljoint_0_conduit_end_reset_n             (<connected-to-balljoint_0_conduit_end_reset_n>),             //                                    .reset_n
		.balljoint_1_conduit_end_scl                 (<connected-to-balljoint_1_conduit_end_scl>),                 //             balljoint_1_conduit_end.scl
		.balljoint_1_conduit_end_sda                 (<connected-to-balljoint_1_conduit_end_sda>),                 //                                    .sda
		.balljoint_1_conduit_end_reset_n             (<connected-to-balljoint_1_conduit_end_reset_n>),             //                                    .reset_n
		.balljoint_2_conduit_end_scl                 (<connected-to-balljoint_2_conduit_end_scl>),                 //             balljoint_2_conduit_end.scl
		.balljoint_2_conduit_end_sda                 (<connected-to-balljoint_2_conduit_end_sda>),                 //                                    .sda
		.balljoint_2_conduit_end_reset_n             (<connected-to-balljoint_2_conduit_end_reset_n>),             //                                    .reset_n
		.balljoint_3_conduit_end_scl                 (<connected-to-balljoint_3_conduit_end_scl>),                 //             balljoint_3_conduit_end.scl
		.balljoint_3_conduit_end_sda                 (<connected-to-balljoint_3_conduit_end_sda>),                 //                                    .sda
		.balljoint_3_conduit_end_reset_n             (<connected-to-balljoint_3_conduit_end_reset_n>),             //                                    .reset_n
		.balljoint_4_conduit_end_scl                 (<connected-to-balljoint_4_conduit_end_scl>),                 //             balljoint_4_conduit_end.scl
		.balljoint_4_conduit_end_sda                 (<connected-to-balljoint_4_conduit_end_sda>),                 //                                    .sda
		.balljoint_4_conduit_end_reset_n             (<connected-to-balljoint_4_conduit_end_reset_n>),             //                                    .reset_n
		.clk_clk                                     (<connected-to-clk_clk>),                                     //                                 clk.clk
		.fancontrol_0_conduit_end_current_average    (<connected-to-fancontrol_0_conduit_end_current_average>),    //            fancontrol_0_conduit_end.current_average
		.fancontrol_0_conduit_end_pwm                (<connected-to-fancontrol_0_conduit_end_pwm>),                //                                    .pwm
		.fancontrol_1_conduit_end_current_average    (<connected-to-fancontrol_1_conduit_end_current_average>),    //            fancontrol_1_conduit_end.current_average
		.fancontrol_1_conduit_end_pwm                (<connected-to-fancontrol_1_conduit_end_pwm>),                //                                    .pwm
		.hps_0_f2h_cold_reset_req_reset_n            (<connected-to-hps_0_f2h_cold_reset_req_reset_n>),            //            hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_debug_reset_req_reset_n           (<connected-to-hps_0_f2h_debug_reset_req_reset_n>),           //           hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_warm_reset_req_reset_n            (<connected-to-hps_0_f2h_warm_reset_req_reset_n>),            //            hps_0_f2h_warm_reset_req.reset_n
		.hps_0_h2f_reset_reset_n                     (<connected-to-hps_0_h2f_reset_reset_n>),                     //                     hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>),       //                        hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),         //                                    .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),         //                                    .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),         //                                    .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),         //                                    .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),         //                                    .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),         //                                    .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),          //                                    .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>),       //                                    .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>),       //                                    .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>),       //                                    .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),         //                                    .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),         //                                    .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3         (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),         //                                    .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_sdio_inst_CMD           (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),           //                                    .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0            (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),            //                                    .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1            (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),            //                                    .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK           (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),           //                                    .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2            (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),            //                                    .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3            (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),            //                                    .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),            //                                    .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),            //                                    .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),            //                                    .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),            //                                    .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),            //                                    .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),            //                                    .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),            //                                    .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),            //                                    .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK           (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),           //                                    .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP           (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),           //                                    .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR           (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),           //                                    .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT           (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),           //                                    .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK          (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),          //                                    .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI         (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),         //                                    .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO         (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),         //                                    .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0          (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),          //                                    .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX           (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),           //                                    .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX           (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),           //                                    .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA           (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),           //                                    .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL           (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),           //                                    .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA           (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),           //                                    .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL           (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),           //                                    .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09        (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),        //                                    .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35        (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),        //                                    .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40        (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),        //                                    .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53        (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),        //                                    .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54        (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),        //                                    .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61        (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),        //                                    .hps_io_gpio_inst_GPIO61
		.icebuscontrol_0_conduit_end_rx              (<connected-to-icebuscontrol_0_conduit_end_rx>),              //         icebuscontrol_0_conduit_end.rx
		.icebuscontrol_0_conduit_end_tx              (<connected-to-icebuscontrol_0_conduit_end_tx>),              //                                    .tx
		.icebuscontrol_0_conduit_end_current_average (<connected-to-icebuscontrol_0_conduit_end_current_average>), //                                    .current_average
		.icebuscontrol_1_conduit_end_rx              (<connected-to-icebuscontrol_1_conduit_end_rx>),              //         icebuscontrol_1_conduit_end.rx
		.icebuscontrol_1_conduit_end_tx              (<connected-to-icebuscontrol_1_conduit_end_tx>),              //                                    .tx
		.icebuscontrol_1_conduit_end_current_average (<connected-to-icebuscontrol_1_conduit_end_current_average>), //                                    .current_average
		.icebuscontrol_2_conduit_end_rx              (<connected-to-icebuscontrol_2_conduit_end_rx>),              //         icebuscontrol_2_conduit_end.rx
		.icebuscontrol_2_conduit_end_tx              (<connected-to-icebuscontrol_2_conduit_end_tx>),              //                                    .tx
		.icebuscontrol_2_conduit_end_current_average (<connected-to-icebuscontrol_2_conduit_end_current_average>), //                                    .current_average
		.icebuscontrol_6_conduit_end_rx              (<connected-to-icebuscontrol_6_conduit_end_rx>),              //         icebuscontrol_6_conduit_end.rx
		.icebuscontrol_6_conduit_end_tx              (<connected-to-icebuscontrol_6_conduit_end_tx>),              //                                    .tx
		.icebuscontrol_6_conduit_end_current_average (<connected-to-icebuscontrol_6_conduit_end_current_average>), //                                    .current_average
		.icebuscontrol_7_conduit_end_rx              (<connected-to-icebuscontrol_7_conduit_end_rx>),              //         icebuscontrol_7_conduit_end.rx
		.icebuscontrol_7_conduit_end_tx              (<connected-to-icebuscontrol_7_conduit_end_tx>),              //                                    .tx
		.icebuscontrol_7_conduit_end_current_average (<connected-to-icebuscontrol_7_conduit_end_current_average>), //                                    .current_average
		.led_external_connection_export              (<connected-to-led_external_connection_export>),              //             led_external_connection.export
		.memory_mem_a                                (<connected-to-memory_mem_a>),                                //                              memory.mem_a
		.memory_mem_ba                               (<connected-to-memory_mem_ba>),                               //                                    .mem_ba
		.memory_mem_ck                               (<connected-to-memory_mem_ck>),                               //                                    .mem_ck
		.memory_mem_ck_n                             (<connected-to-memory_mem_ck_n>),                             //                                    .mem_ck_n
		.memory_mem_cke                              (<connected-to-memory_mem_cke>),                              //                                    .mem_cke
		.memory_mem_cs_n                             (<connected-to-memory_mem_cs_n>),                             //                                    .mem_cs_n
		.memory_mem_ras_n                            (<connected-to-memory_mem_ras_n>),                            //                                    .mem_ras_n
		.memory_mem_cas_n                            (<connected-to-memory_mem_cas_n>),                            //                                    .mem_cas_n
		.memory_mem_we_n                             (<connected-to-memory_mem_we_n>),                             //                                    .mem_we_n
		.memory_mem_reset_n                          (<connected-to-memory_mem_reset_n>),                          //                                    .mem_reset_n
		.memory_mem_dq                               (<connected-to-memory_mem_dq>),                               //                                    .mem_dq
		.memory_mem_dqs                              (<connected-to-memory_mem_dqs>),                              //                                    .mem_dqs
		.memory_mem_dqs_n                            (<connected-to-memory_mem_dqs_n>),                            //                                    .mem_dqs_n
		.memory_mem_odt                              (<connected-to-memory_mem_odt>),                              //                                    .mem_odt
		.memory_mem_dm                               (<connected-to-memory_mem_dm>),                               //                                    .mem_dm
		.memory_oct_rzqin                            (<connected-to-memory_oct_rzqin>),                            //                                    .oct_rzqin
		.power_control_0_external_connection_export  (<connected-to-power_control_0_external_connection_export>),  // power_control_0_external_connection.export
		.power_sense_0_external_connection_export    (<connected-to-power_sense_0_external_connection_export>),    //   power_sense_0_external_connection.export
		.reset_reset_n                               (<connected-to-reset_reset_n>),                               //                               reset.reset_n
		.switches_0_external_connection_export       (<connected-to-switches_0_external_connection_export>)        //      switches_0_external_connection.export
	);

